stages:
  - test
  - build
  - deploy

build-vite:
  stage: build
  image: node
  script:
    - cd Frontend
    - npm i
    - npm run build  

pages:
  stage: deploy    
  script:
    - cd Frontend
    - mkdir .public
    - cp -r dist/* .public
    - mv .public public
    - ls
    - ls ./public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - ./Frontend/ 
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
