stages:
  - test
  - build
  - deploy

build-vite:
  stage: build
  image: node
  script:
    - cd Frontend
    - npm i
    - npm run build
  artifacts:
    paths:
      - Frontend/public/

pages:
  stage: deploy    
  script:
    - cd Frontend    
    - mkdir .public
    - cp -r dist/* public/  
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
