stages:
  - test
  - build
  - deploy

build-vite:
  stage: build
  image: node
  script:
    - cd Frontend
    - npm i
    - npm run build

pages:
  stage: deploy
  # Functions that should be executed before the build script is run
  before_script: []
  # The Docker image that will be used to build your app
  image: node
  script:
    - cd Frontend
    - npm i
    - npm run build
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - ./Frontend/public/
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
