# Use the official MySQL image from Docker Hub
FROM gradle:latest


# Copy files (if any)
COPY ./ ./spring-demo

# Expose the MySQL port
#EXPOSE 3306

# Start MySQL when the container starts
CMD ["bash"]
